# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54f5650f93c1256d352dba1bd5bcfa398965c44366bfafa8df3114963cf7a5b641b7fee0e4ad2eed83a885885bd04e42949053bc9d2d6187c167b010beae92c8

test:
  secret_key_base: 4a4ae85f6f9c0122d3c59a0b683793a142ff9ade7c381cff93453edb1c373f70f17f8e5c7500eafd55620c4da404b749bd0ac91eb01bb5483e467852112aaefb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
